name: deploy-devel
on:
  push:
    branches:
      - devel
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: mvn clean test
  build-and-deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build_and_deploy
        run: |
          mvn clean package -DskipTests
          fileName=$(basename $(ls ./target/*.jar))
          cp ./target/$fileName /opt/webapps/JavaUno/devel/$fileName
          ln -sf /opt/webapps/JavaUno/devel/$fileName /opt/webapps/JavaUno/devel/JavaUno.jar