name: deploy-live
on:
  push:
    branches:
      - live
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: mvn clean test
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build_and_deploy
        run: |
          mvn clean package -DskipTests
          fileName=$(basename $(ls ./target/*.jar))
          cp ./target/$fileName /opt/webapps/JavaUno/live/$fileName
          ln -sf /opt/webapps/JavaUno/live/$fileName /opt/webapps/JavaUno/live/JavaUno.jar
          cp /opt/webapps/JavaUno/live/next-config.sh /opt/webapps/JavaUno/live/config.sh
          touch /opt/webapps/JavaUno/live/restart